### PR TITLE
Fix unit tests

### LINKED ISSUE #2: Fix test suite
Currently there's two out of three tests failing.

### PR DESCRIPTION
**Pull request by wilr**
Fixes #2

### CODE REVIEW

File: src/Model/ElementForm.php [hunk 1]
```diff
@@ -41,18 +41,33 @@ public function ElementForm()
         $current = Controller::curr();
 
         if ($current && $current->getAction() == 'finished') {
-            return $controller->renderWith('ReceivedFormSubmission');
+            return $controller->renderWith(UserDefinedFormController::class .'_ReceivedFormSubmission');
```
Comment (robbieaverill) [inline src/Model/ElementForm.php]: Is this logic from userforms? I quite like the idea of swapping the `_` for a `\` and making it a new folder and `ReceivedFormSubmission.ss` file, but if it's mimicking userforms logic it's fine :)

**Comment by robbieaverill** [comment]
@wilr do you know why this might not be working on postgres?

**Comment by robbieaverill** [comment]
Rebased and commented out the Postgres build in Travis, I'll log an issue to fix this separately
